# Generated by Django 5.0.7 on 2024-07-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=200)),
                ('ptopic', models.CharField(max_length=200)),
                ('plangauges', models.CharField(max_length=200)),
                ('pduration', models.IntegerField(help_text='Enter in days')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('sem', models.IntegerField()),
            ],
        ),
    ]
